
package com.main.ws.service.impl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import com.main.ws.service.ObjectFactory;
import com.main.ws.service.User;
import com.main.ws.service.UserArray;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserService", targetNamespace = "http://service.ws.main.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserService {


    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.ws.main.com/UserService/deleteUserRequest", output = "http://service.ws.main.com/UserService/deleteUserResponse")
    public boolean deleteUser(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.ws.main.com/UserService/addUserRequest", output = "http://service.ws.main.com/UserService/addUserResponse")
    public boolean addUser(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0,
        @WebParam(name = "arg1", partName = "arg1")
        String arg1,
        @WebParam(name = "arg2", partName = "arg2")
        int arg2);

    /**
     * 
     * @return
     *     returns com.main.ws.service.UserArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.ws.main.com/UserService/getUsersRequest", output = "http://service.ws.main.com/UserService/getUsersResponse")
    public UserArray getUsers();

    /**
     * 
     * @param arg0
     * @return
     *     returns com.main.ws.service.User
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://service.ws.main.com/UserService/getUserRequest", output = "http://service.ws.main.com/UserService/getUserResponse")
    public User getUser(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

}
